title:       "Operating Systems 2021-1 (OS211)"
version:     "1.04---30-Mar-2021"
copyright:   "2021-2021"
description: >- 
  Menggokil!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Valentino Herdyan Permadi"
address:          "Bekasi"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://valentinohp.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/valentinohp/os211/"
urlghpage:        "https://valentinohp.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

